name: atos
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- python=3.9
- numpy>=1.21.6
- setuptools>=40.1.0
- pip
- matplotlib
- pandas
- keras
- tensorflow
- pip:
  - qiskit
  - qlmaas
  - sklearn